Nav_links:
  type: list
  default: "Under Consideration;Features under consideration;/tags/c/submit-an-idea/5/none/under-consideration/|On Roadmap;on roadmap;/tags/c/submit-an-idea/5/none/on-roadmap/|Not on Roadmap;Not on roadmap;/tags/c/submit-an-idea/5/none/not-on-roadmap/|Released;Released Features;/tags/c/submit-an-idea/5/none/released/"
  description:
    en: |
      Semicolon delimited in this order: <strong>display name;description;URL</strong>
      <br/><strong>Display name:</strong> text that shows on the menu
      <br/><strong>Description:</strong> text that shows on hover
      <br/><strong>URL:</strong> the link (e.g., <code>/latest</code> or <code>https://discourse.org</code>)
Hide_dropdowns:
  default: false
  description:
    en: "Hide category and tag dropdowns"
Hide_default_links:
  default: false
  description:
    en: "Hide the default links on both mobile and desktop."
