Nav_links:
  type: list
  default: "All requests;All requested features;/c/feature-requests/7/all|New;Newly requested features;/c/feature-requests/7/all?ascending=false&order=created|Under Consideration;Features under consideration;/tags/c/feature-requests/7/none/under-consideration|On Roadmap;on roadmap;/tags/c/feature-requests/7/none/on-roadmap|Released;Released Features;/tags/c/feature-requests/7/none/released|Long-term Roadmap;Long-term roadmap;/tags/c/feature-requests/7/none/long-term-roadmap"
  description:
    en: |
      Semicolon delimited in this order: <strong>display name;description;URL</strong>
      <br/><strong>Display name:</strong> text that shows on the menu
      <br/><strong>Description:</strong> text that shows on hover
      <br/><strong>URL:</strong> the link (e.g., <code>/latest</code> or <code>https://discourse.org</code>)
Hide_dropdowns:
  default: false
  description:
    en: "Hide category and tag dropdowns"
Hide_default_links:
  default: false
  description:
    en: "Hide the default links on both mobile and desktop."
